export enum Task {
    IMAGE_CLASSIFICATION = 'IMAGE_CLASSIFICATION',
    OBJECT_DETECTION = 'OBJECT_DETECTION',
    TABULAR_CLASSIFICATION = 'TABULAR_CLASSIFICATION',
    TEXT_CLASSIFICATION = 'TEXT_CLASSIFICATION'
}